server:
  port: 3000
eureka:
  server:
    enable-self-preservation: false #是否开启自我保护模式，默认为true; Eureka 会统计15分钟之内心跳失败的比例低于85%将会触发保护机制，不剔除服务提供者，如果关闭服务注册中心将不可用的实例正确剔除
    eviction-interval-timer-in-ms: 10000 #Eureka Server清理无效节点的时间间隔(单位:毫秒 默认是60*1000)
  instance:
    hostname: 127.0.0.1

  client:
    registerWithEureka: false #表示是否将自己注册到Eureka Server，默认为true(集群时需要为true)
    fetchRegistry: false #表示是否从Eureka Server获取注册信息，默认为true(集群时需要为true)。[不需要从服务端获取注册信息(因为在这里自己就是服务端,而且已经禁用自己注)]
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server #此实例注册到eureka服务端的name(后续集群的名称)